version: '3'

services:
  agent:
    image: gcr.io/spiralpower/buildkite-agent:latest
    env_file:
      - secrets/secret.env
    environment:
      BUILDKITE_AGENT_NAME: "swarm-${BUILDSWARM_CLUSTER}-%hostname"
    volumes:
      - ./secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
