#!/bin/bash

set -euo pipefail

# because people are fools
chmod 600 /buildkite-secrets/id_rsa_buildkite_git

# register the mounted key
eval "$(ssh-agent -s)"
ssh-add -k /buildkite-secrets/id_rsa_buildkite_git

# You can export other secrets here too
# export FOO=bar
